spring.application.name=backend
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/life_manager
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true

# JWT Configuration
jwt.secret=CoeSsqoaH7XOryCEk0cq6yrFrnWLoN7sGVWyVpWTjss
jwt.expiration=360000